import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Compiled JS counterparts of TS files (auto-generated by tsc)
    "src/lib/payroll/*.js",
    // Root-level seed/test/verify scripts — plain Node CJS scripts, not app code
    "*.js",
    "*.cjs",
    "*.mjs",
    "scratch/**",
    "test-*.ts",
    "test-*.js",
    "verify-*.ts",
    "verify-*.js",
    "seed-*.ts",
    "seed-*.js",
    "fill-missing.js",
    "create-admin.js",
    "jest.config.js",
  ]),
  // Project-wide rule overrides
  {
    rules: {
      // This codebase uses `any` extensively at data boundaries (Supabase, RHF, etc.)
      // Downgrade from error → warn so the build is not blocked.
      "@typescript-eslint/no-explicit-any": "warn",
      // Unused vars are common in WIP code — warn only.
      "@typescript-eslint/no-unused-vars": "warn",
      // The set-state-in-effect pattern (calling an async loader inside useEffect)
      // is intentional and safe in this project — suppress the false positive.
      "react-hooks/set-state-in-effect": "off",
      // useEffect dependency arrays are managed manually throughout — warn only.
      "react-hooks/exhaustive-deps": "warn",
      // @ts-ignore is acceptable in a few places; prefer-ts-expect-error is good practice
      // but not enforced as an error here.
      "@typescript-eslint/ban-ts-comment": "warn",
      // window.location.href is used in a few intentional full-page redirects.
      "@next/next/no-location-assign-relative-destination": "warn",
      // Unescaped entities are common in copy text — downgrade to warn.
      "react/no-unescaped-entities": "warn",
      // Incompatible library warning from React Compiler — informational only.
      "react-hooks/incompatible-library": "warn",
    },
  },
]);

export default eslintConfig;
