export const SYSTEM_DEDUCTION_DESCRIPTIONS = {
  TAX: "BIR Withholding Tax",
  SSS_REGULAR: "SSS Regular Contribution",
  SSS_WISP: "SSS WISP (MPF)",
  SSS_EC: "SSS EC (Employer Paid)",
  SSS_NOT_APPLICABLE: "SSS (Not Applicable)",
  PHILHEALTH_PREMIUM: "PhilHealth Premium",
  PHILHEALTH_NOT_APPLICABLE: "PhilHealth (Not Applicable)",
  PAGIBIG_CONTRIBUTION: "Pag-IBIG Contribution",
  PAGIBIG_NOT_APPLICABLE: "Pag-IBIG (Not Applicable)",
};

export const STATUTORY_DEDUCTION_DESCRIPTIONS = [
  SYSTEM_DEDUCTION_DESCRIPTIONS.SSS_REGULAR,
  SYSTEM_DEDUCTION_DESCRIPTIONS.SSS_WISP,
  SYSTEM_DEDUCTION_DESCRIPTIONS.PHILHEALTH_PREMIUM,
  SYSTEM_DEDUCTION_DESCRIPTIONS.PAGIBIG_CONTRIBUTION,
];

export const SYSTEM_EARNING_DESCRIPTIONS = {
  BASIC_SALARY: "Basic Salary (Calculated)",
};

